"""Initial schema setup

Revision ID: 69c9c017238c
Revises: 
Create Date: 2025-11-04 21:12:39.503172

"""
from typing import Sequence, Union

import sqlmodel

#追記↑

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c9c017238c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prefecture', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('income_band', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('school_band', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('major', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_social_care', sa.Boolean(), nullable=False),
    sa.Column('target_period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('has_volunteer', sa.Boolean(), nullable=False),
    sa.Column('has_cram', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_grade'), 'profile', ['grade'], unique=False)
    op.create_index(op.f('ix_profile_has_social_care'), 'profile', ['has_social_care'], unique=False)
    op.create_index(op.f('ix_profile_income_band'), 'profile', ['income_band'], unique=False)
    op.create_index(op.f('ix_profile_prefecture'), 'profile', ['prefecture'], unique=False)
    op.create_table('scholarship',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_per_year', sa.Integer(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eligible_grades', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('eligible_prefs', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('fields', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('income_requirement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('other_requirements', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('required_docs', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('application_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty_hint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarship_deadline'), 'scholarship', ['deadline'], unique=False)
    op.create_index(op.f('ix_scholarship_is_published'), 'scholarship', ['is_published'], unique=False)
    op.create_index(op.f('ix_scholarship_name'), 'scholarship', ['name'], unique=False)
    op.create_table('matchresult',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('why_match', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('amount_per_year', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('todo', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('scholarship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchresult_profile_id'), 'matchresult', ['profile_id'], unique=False)
    op.create_index(op.f('ix_matchresult_scholarship_id'), 'matchresult', ['scholarship_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matchresult_scholarship_id'), table_name='matchresult')
    op.drop_index(op.f('ix_matchresult_profile_id'), table_name='matchresult')
    op.drop_table('matchresult')
    op.drop_index(op.f('ix_scholarship_name'), table_name='scholarship')
    op.drop_index(op.f('ix_scholarship_is_published'), table_name='scholarship')
    op.drop_index(op.f('ix_scholarship_deadline'), table_name='scholarship')
    op.drop_table('scholarship')
    op.drop_index(op.f('ix_profile_prefecture'), table_name='profile')
    op.drop_index(op.f('ix_profile_income_band'), table_name='profile')
    op.drop_index(op.f('ix_profile_has_social_care'), table_name='profile')
    op.drop_index(op.f('ix_profile_grade'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
